export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const LOAD_CART = "LOAD_CART";
export const ACTIVATE_SHOPPING_BUTTON = "ACTIVATE_SHOPPING_BUTTON";
export const DEACTIVE_SHOPPING_BUTTON = "DEACTIVATE_SHOPPING_BUTTON";